spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    # テスト用。実際は環境変数を使用して指定する。
    url: jdbc:postgresql://localhost:5432/health_point?user=health_point_user&password=41934193
    driverClassName: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true

mybatis:
  mapper-locations: classpath*:/mapper/*.xml